from app.models import db, Item



def seed_items():
    items = []

    # Hot Coffee
    items.append(Item(name = 'Caffè Americano',calories = 15, price = 3.25 , description='Espresso shots topped with hot water create a light layer of crema culminating in this wonderfully rich cup with depth and nuance.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/f12bc8af498d45ed92c5d6f1dac64062.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Veranda Blend',calories = 5, price = 3.55 , description='In Latin America, coffee farms are often run by families, with their own homes on the same​ land where their coffee grows. We’ve sipped coffee with these farmers for decades,​ sitting on their verandas, overlooking the lush beauty of the coffee trees rolling out in the​ distance. Most times it was a lightly roasted coffee like this one. It took us more than 80​ tries to get it right—mellow and flavorful with a nice softness.​',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/2c8f40a3b37648539d74e271479b3f9a.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Caffè Misto',calories = 110, price = 4.25 , description='A one-to-one combination of fresh-brewed coffee and steamed milk add up to one distinctly delicious coffee drink remarkably mixed.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/d668acbc691b47249548a3eeac449916.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Feature Dark Roast Coffee',calories = 5, price = 2.99 , description='This full-bodied dark roast coffee with bold, robust flavors showcases our roasting and blending artistry—an essential blend of balanced and lingering flavors.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/0279f9c5fa5941d2a65dd183d7a0b386.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Feature Medium Roast - Fremont Valley Roast',calories = 5, price = 3.10 , description='From our first store in Fremont to our coffeehouses around the world, customers requested a freshly brewed coffee they could enjoy throughout the day. In 2022 our master blenders and roasters created this for you—a smooth, well-rounded blend of Latin American coffees with subtly rich flavors of chocolate and toasted nuts, it’s served fresh every day at a store near you.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/bffaf0f27e124801abcabe09f05b0fb2.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Decaf Pike Place Roast',calories = 5, price = 3.10 , description='From our first store in Fremont to our coffeehouses around the world, customers requested a freshly brewed coffee they could enjoy throughout the day. In 2022 our master blenders and roasters created this for you—a smooth, well-rounded blend of Latin American coffees with subtly rich flavors of chocolate and toasted nuts, it’s served fresh every day at a store near you.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/bffaf0f27e124801abcabe09f05b0fb2.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Cappuccino',calories = 140, price = 4.60 , description='Dark, rich espresso lies in wait under a smoothed and stretched layer of thick milk foam. An alchemy of barista artistry and craft.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/5c515339667943ce84dc56effdf5fc1b.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Expresso',calories = 10, price = 2.25 , description='Our smooth signature Espresso Roast with rich flavor and caramelly sweetness is at the very heart of everything we do.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/ec519dd5642c41629194192cce582135.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Expresso Con Panna',calories = 35, price = 2.75 , description='Espresso meets a dollop of whipped cream to enhance the rich and caramelly flavors of a straight-up shot.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/e9330b18ae524e69bdcbe97460d6f5bb.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Flat White',calories = 170, price = 5.25 , description='Smooth ristretto shots of espresso get the perfect amount of steamed whole milk to create a not-too-strong, not-too-creamy, just-right flavor.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/fedee22e49724cd09fbcc7ee2e567377.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Honey Almondmilk Flat White',calories = 120, price = 5.25 , description='This flat white intentionally pairs almondmilk and Blonde Espresso Roast with a hint of honey, making a perfect amount of creamy, nutty sweetness.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/77801559b72b469583f4d484adc1bfa7.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Pumpkin Spice Latte',calories = 390, price = 6.25 , description='Our signature espresso and steamed milk with the celebrated flavor combination of pumpkin, cinnamon, nutmeg and clove. Enjoy it topped with whipped cream and real pumpkin-pie spices.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/895d6b3916c14ad6862d88ce282e8838.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Caffe Latte',calories = 190, price = 4.75 , description='Our dark, rich espresso balanced with steamed milk and a light layer of foam. A perfect milk-forward warm-up.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/b635f407bbcd49e7b8dd9119ce33f76e.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Cinnamon Dolce Latte',calories = 340, price = 6.25 , description='We add freshly steamed milk and cinnamon dolce-flavored syrup to our classic espresso, topped with sweetened whipped cream and a cinnamon dolce topping to bring you specialness in a treat.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/284e1571faa748f2889d0b566b71d578.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Blonde Vanilla Latte',calories = 250, price = 6.25 , description='Extra-smooth Starbucks® Blonde Espresso, velvety steamed milk and vanilla syrup come together to create a delightful new twist on a beloved espresso classic. An ideal cup for those who prefer a lighter-roasted coffee.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/b635f407bbcd49e7b8dd9119ce33f76e.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Apple Crisp Oatmilk Macchiato',calories = 320, price = 5.33 , description='Pairs well with crisp mornings.Discover the nondairy layers of Apple Crisp Oatmilk Macchiato',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/ea64c8877aa1400fa0b76de8210ad543.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Caramel Macchiato',calories = 250, price = 5.33 , description='Freshly steamed milk with vanilla-flavored syrup marked with espresso and topped with a caramel drizzle for an oh-so-sweet finish.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/58db701349cb48738069e8c912e2b3ac.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Espresso Macchiato',calories = 15, price = 4.00 , description='Our rich espresso marked with dollop of steamed milk and foam. A European-style classic.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/26495f2a8b644fe8960dd74e1891b7b7.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Caffe Mocha',calories = 370, price = 5.25 , description='Our rich, full-bodied espresso combined with bittersweet mocha sauce and steamed milk, then topped with sweetened whipped cream. The classic coffee drink that always sweetly satisfies.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/915736da018842e788147f7eab73db73.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'White Chocolate Mocha',calories = 430, price = 6.99 , description='Our signature espresso meets white chocolate sauce and steamed milk, and then is finished off with sweetened whipped cream to create this supreme white chocolate delight.',drink_category = 'Hot coffees',image_url="https://globalassets.starbucks.com/assets/3eab25199e994b689fa5c047fc31f217.jpg?impolicy=1by1_wide_topcrop_630"))

    # Hot Tea
    items.append(Item(name = 'Chai Tea Latte',calories = 240, price = 3.99 , description='Black tea infused with cinnamon, clove and other warming spices is combined with steamed milk and topped with foam for the perfect balance of sweet and spicy. An iconic chai cup.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/2d52f16a22fb40ff898be1815ecc952e.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Royal English Breakfast Tea',calories = 0, price = 3.25 , description='Each sip of this beloved morning black tea unfolds to reveal the complexity of the high-grown full leaves. An elegant, time-honored classic that brings a royal nod to every cup.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/e3554d07d1394ee79cfad80a383ba163.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Royal English Breakfast Tea Latte',calories = 150, price = 4.99 , description='A select blend of rich, full-leaf black teas from India and Sri Lanka sweetened with liquid cane sugar and topped with steamed milk and a velvety foam. Each and every sip—smooth and silky.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/919eb07194f44a0b842c0260c3a286d8.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Earl Grey Tea',calories = 0, price = 3.25 , description='We take a strong black tea base and add the essence of bergamot, a citrus fruit with subtle lemon and floral lavender notes, to create this aromatically awesome tea flavor.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/6f780d5d392542c6b9b1a4412881cecc.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Emperor\'s Clouds & Mist',calories = 0, price = 3.25 , description='This gently smoky, softly sweet green tea—cultivated at 3,500 feet and shrouded in ethereal clouds and mist—is tasty no matter what language you say it in.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/1a84d455abd84ac3b356c6523fce9ac8.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Matcha Tea Latte',calories = 240, price = 4.99 , description='Smooth and creamy matcha sweetened just right and served with steamed milk. This favorite will transport your senses to pure green delight.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/8b1b6d808cca4787afd2b30cf8dd5676.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Honey Citrus Mint Tea',calories = 130, price = 3.99 , description='A customer creation so popular it’s now on the menu. Jade Citrus Mint green tea, Peach Tranquility herbal tea, hot water, steamed lemonade and a touch of honey mingle tastefully well together for a tea that comforts from the inside out.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/a5e64777b3cc412e9239b8a37328cb37.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Jade Citrus Mint Brewed Tea',calories = 0, price = 3.25 , description='Green tea, lemon verbena, lemongrass and a hint of spearmint mingle for a bright, refreshing, citrusy green tea experience.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/6a59c09bb55c42f8a6a970e73c22caeb.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Mint Majesty',calories = 0, price = 3.50 , description='A blend of mint and a pinch of lemon verbena creates a refreshing flavor that\'s supercool for a caffeine-free herbal tea.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/cf7469c84a444e4f9a341f8023558c77.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Peach Tranquility',calories = 0, price = 3.50 , description='A sweet fusion of peach, candied pineapple, chamomile blossoms, lemon verbena and rose hips come together in this caffeine-free herbal tea. Sip back and relax.',drink_category = 'Hot tea',image_url="https://globalassets.starbucks.com/assets/f3ecda7d7510434c9ed2b3167dcb4466.jpg?impolicy=1by1_wide_topcrop_630"))

    # Hot Drink
    items.append(Item(name = 'Hot Chocolate',calories = 370, price = 4.99 , description='Steamed milk with vanilla- and chocolate-flavored syrups. Topped with sweetened whipped cream and chocolate-flavored drizzle. A timeless classic made to sweeten your spirits.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/677d276173ec4bc192c2b9a21776339f.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'White Hot Chocolate',calories = 440, price = 5.40 , description='A traditional hot chocolate beverage made with white chocolate sauce and steamed milk, topped with whipped cream.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/6b385ad21e7245788eb2d2754ab6f823.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Caramel Apple Spice',calories = 380, price = 4.99 , description='Steamed apple juice complemented with cinnamon syrup, whipped cream and a caramel sauce drizzle.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/39bab62a29214270b6b30eb838e2c5a6.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Steamed Apple Juice',calories = 220, price = 2.99 , description='Freshly steamed 100% apple juice (not from concentrate). Feel the apple goodness in this classic fruit drink that will soothe and embolden your day.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/a9e551eb323e4f0a93cf91b165916950.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Pumpkin Spice Crème',calories = 400, price = 6.99 , description='We combine steamed milk with flavors of pumpkin, cinnamon, nutmeg and clove, then top it all off with whipped cream to create this amazing, coffee-free fall favorite.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/e1b9156fb2514205a1abd1828d5ffb7b.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Steamed Milk',calories = 200, price = 1.50 , description='Enjoy a warm cup of skim, 2%, soy, almond or coconutmilk steamed for your sipping pleasure.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/8b656cabb99344269543833b7e787bbd.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Vanilla Crème',calories = 350, price = 4.99 , description='A smooth, frothy vanilla flavoured luxury. For those times when you’d rather not indulge in the rich flavour of our world-famous espresso - but still desire a hot, creamy vanilla beverage.',drink_category = 'Hot drink',image_url="https://globalassets.starbucks.com/assets/3f61a806f6ff4bc38e2e5fc0d0eef97c.jpg?impolicy=1by1_wide_topcrop_630"))

    # Cold Coffee
    items.append(Item(name = 'Pumpkin Cream Cold Brew',calories = 250, price = 4.99 , description='Cold Brew sweetened with vanilla syrup and topped with a pumpkin cream cold foam and a dusting of pumpkin spice topping.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/b2841a2f51744869932c31834909f0e9.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Salted Caramel Cream Cold Brew',calories = 220, price = 5.25 , description='Here\'s a savory-meets-sweet refreshing beverage certain to delight: our signature, super-smooth cold brew, sweetened with a touch of caramel and topped with a salted, rich cold foam.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/64da774b521447f690c20290cd4cb29d.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Cold Brew Coffee',calories = 5, price = 4.50 , description='Handcrafted in small batches daily, slow-steeped in cool water for 20 hours, without touching heat—Cold Brew is made from our custom blend of beans grown to steep long and cold for a super-smooth flavor.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/103b2b745f4848f884b793696a4573b6.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Vanilla Sweet Cream Cold Brew',calories = 110, price = 5.25 , description='Our slow-steeped custom blend of Cold Brew coffee accented with vanilla and topped with a delicate float of house-made vanilla sweet cream that cascades throughout the cup. It\'s over-the-top and super-smooth.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/07951b9a7d7d47a2892dfa7a707fd318.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Nitro Cold Brew',calories = 5, price = 5.49 , description='Our small-batch cold brew—slow-steeped for a super-smooth taste—gets even better. We\'re infusing it with nitrogen to create a sweet flavor without sugar and cascading, velvety crema. Perfection is served.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/8c5dcfa053504f85b3e7af2fa451346d.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Caffè Americano',calories = 15, price = 3.99 , description='Espresso shots topped with cold water produce a light layer of crema, then served over ice. The result: a wonderfully rich cup with depth and nuance. Pro Tip: For an additional boost, ask your barista to try this with an extra shot.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/921a409e6f55407da52eee4c8ad13ada.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Toasted Vanilla Oatmilk Shaken Espresso',calories = 140, price = 4.75 , description='Blonde espresso combined with notes of caramelized vanilla shaken together and topped with oatmilk for an energizing treat to boost your day.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/9a51e00fff1c42e8acb62fcbfcef8838.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Brown Sugar Oatmilk Shaken Espresso',calories = 120, price = 4.99 , description='First we shake Blonde espresso, brown sugar and cinnamon together, and then top it off with oatmilk and ice for a cool lift to power you through your day.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/5bfe4972905a400c97717ce4176ebe92.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Honey Almondmilk Flat White',calories = 100, price = 3.99 , description='This iced flat white—intentionally made with almondmilk and Blonde Espresso Roast poured over ice with a hint of honey—creates a perfect amount of cool, creamy, nutty sweetness.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/a651497f08314edd9a213950c2865e8c.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Caramel Macchiato',calories = 250, price = 5.25 , description='We combine our rich, full-bodied espresso with vanilla-flavored syrup, milk and ice, then top it off with a caramel drizzle for an oh-so-sweet finish.',drink_category = 'Cold coffee',image_url="https://globalassets.starbucks.com/assets/363835b1db024636adeb4089ebb96291.jpg?impolicy=1by1_wide_topcrop_630"))

    # Iced Tea
    items.append(Item(name = 'Iced Black Tea',calories = 0, price = 3.25, description='Premium black tea sweetened just right and shaken with ice to create an ideal iced tea—a rich and flavorful black tea journey awaits you.',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/f56f2f6798504d72812581fbd3c326b8.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Royal English Breakfast Tea Latte',calories = 140, price = 3.80, description='A select blend of rich, full-leaf black teas from India and Sri Lanka sweetened with liquid cane sugar and combined with milk and ice.',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/c21355c84f60481da265614667b168d8.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Peach Green Tea',calories = 60, price = 3.25, description='Green tea is layered together with flavors of spearmint, lemon verbena and lemongrass for a taste that’s really peachy keen.',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/2e363c918bc74d05965eb6e635293d00.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Matcha Tea Latte',calories = 200, price = 4.65, description='Smooth and creamy matcha sweetened just right and served with milk over ice. Green has never tasted so good.',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/08f75b01cd3c46af9d8665c5912341e7.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Green Tea Lemonade',calories = 50, price = 4.25, description='Green tea blended with mint, lemongrass, lemon verbena and lemonade, and given a good shake with ice. Lightly flavored and oh-so-refreshing!',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/9d6748ad5ded472da7a03d0d99a1f8a7.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Matcha Lemonade',calories = 120, price = 3.25, description='Our finely ground matcha green tea combined with crisp lemonade, then shaken with ice, creates a refreshingly sweet, delicious drink and a delightfully vibrant, green hue.',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/730f5d78c6304eda88c960734fb1a8a4.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Iced Passion Tango Tea',calories = 0, price = 3.25, description='A blend of hibiscus, lemongrass and apple hand-shaken with ice: a refreshingly vibrant tea infused with the color of passion',drink_category = 'Iced tea',image_url="https://globalassets.starbucks.com/assets/8b91a3ac49114445b4b6f2acf58a03ec.jpg?impolicy=1by1_wide_topcrop_630"))

    # Cold Drink
    items.append(Item(name = 'Dragon Drink Refreshers Beverage',calories = 130, price = 6.25, description='This tropical-inspired pick-me-up—crafted with sweet mango and dragonfruit flavors and hand-shaken with creamy coconutmilk, ice and a scoop of real diced dragonfruit--creates a refreshing and surprising delight in the fall.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/358b62402a844a3e9567d70a9790032f.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Mango Dragonfruit Refreshers Beverage',calories = 90, price = 6.25, description='A tropical-inspired pick-me-up--crafted with a refreshing combination of sweet mango and dragonfruit flavors and hand-shaken with ice plus a scoop of real diced dragonfruit.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/c51376156a204e69aba133d3b9009171.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Paradise Drink Refreshers Beverage',calories = 140, price = 6.25, description='Tropical flavors of pineapple and passionfruit combine with diced pineapple and creamy coconutmilk to create a delicious island escape.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/7ef4d20aa4ed4587ac02b0e694edceef.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Strawberry Açaí Lemonade Refreshers Beverage',calories = 140, price = 5.75, description='Sweet strawberry flavors, passion fruit and açaí notes balanced with the delightful zing of lemonade, served over ice with freeze-dried strawberry pieces. The ultimate pick-me-up your afternoon is calling for.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/0a7f3df9fe5b4152940bd84bb2bea7f3.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Pineapple Passionfruit Refreshers Beverage',calories = 100, price = 5.25, description='Tropical flavors of pineapple and passionfruit mix with diced pineapple to create an island escape--oh so refreshing.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/a81d75c9b8914b00912006411fa2f095.jpg?impolicy=1by1_wide_topcrop_630"))
    items.append(Item(name = 'Pink Drink Refreshers Beverage',calories = 140, price = 5.25, description='Our crisp Strawberry Açaí Refreshers® beverage--with accents of passion fruit and combined with creamy coconutmilk--evokes a fruity and refreshing sip of spring, no matter what time of year.',drink_category = 'Cold drink',image_url="https://globalassets.starbucks.com/assets/e0cd6e8588b6431d9d6f702bde6ee41c.jpg?impolicy=1by1_wide_topcrop_630"))

    for item in items:
        db.session.add(item)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_items():
    db.session.execute('TRUNCATE items RESTART IDENTITY CASCADE;')
    db.session.commit()


# from alembic import op

# op.bulk_insert(Item.__table__,
#     [
#         {
#         'id': 1,
#         'name':'Test 1',
#         'calories': 200,
#         'price': 5.25,
#         'description': 'testest',
#         'drink_category': 'cold balck tea',
#         "image_url":"test"
#         },
#         {
#         'id': 2,
#         'name':'Test 2',
#         'calories': 200,
#         'price': 5.25,
#         'description': 'testest',
#         'drink_category': 'cold balck tea',
#         "image_url":"test"
#         }
#    ])
